Add Raw Lidar Readings to 3-space Direction Vector Formula as a Crate
BradenEverson/driem pull request #35
Opened 2024-11-12 21:43 UTC by BradenEverson

Credit to Matthew for the actual formula and underlying MatLab code I used as a reference.

2024-11-12 22:22 UTC, MattTheRoboMan commented on earthmover-lidar/src/lib.rs
This offset would be from the center of rotation, not the accelerometer.

2024-11-12 22:23 UTC, MattTheRoboMan commented on earthmover-lidar/src/lib.rs
> +/// Given a lidar's roll, pitch and raw angles, alongside a set of fixed offsets from an
This offset would be from the center of rotation, not the accelerometer.

2024-11-12 22:27 UTC, MattTheRoboMan requested changes
I made one comment on one of your comments. You mentioned an offset from the accelerometer, but the offset is actually from the center of rotation of the gimbal.

2024-11-13 06:12 UTC, MattTheRoboMan requested changes

2024-11-13 06:12 UTC, MattTheRoboMan commented on earthmover-lidar/src/lib.rs
> +    // Solve for Vector D
You had the offset_P multiplied by the R vector, not the P vector. The following three lines should be:
 +   let d_x = (distance * l_x) + (OFFSET_P * p_x) + (OFFSET_R * r_x) + (OFFSET_N * nu_x);
 +   let d_y = (distance * l_y) + (OFFSET_P * p_y) + (OFFSET_R * r_y) + (OFFSET_N * nu_y);
 +   let d_z = (distance * l_z) + (OFFSET_P * p_z) + (OFFSET_R * r_z) + (OFFSET_N * nu_z);

2024-11-13 06:12 UTC, MattTheRoboMan commented on earthmover-lidar/src/lib.rs
> +    // N1 magnitude
I used `nl` for the Normal LIDAR vector not `n1`. (L vs 1). I'm not sure how important it is, but it is something I noticed.

2024-11-13 06:12 UTC, MattTheRoboMan commented on earthmover-lidar/src/lib.rs
> +/// Offset along p
I looked at the data sheet and I can't tell if the measurement is in meters or mm but here are the offset values converted to meters:
oP = -13.2842*10^(-3); % offset along P [m] (-0.523 in)
oN = 40.8432*10^(-3); % offset along Nu [m] (1.608 in)
oR = -0.1016*10^(-3); % offset along R [m] (-0.004 in)

We should run some tests to check which unit it is outputting and adjust the offset accordingly. This is the only part where units are important because it is based off of a real-world measurement, but it makes everything else dependent on having the correct units.

2024-11-13 06:12 UTC, MattTheRoboMan commented on earthmover-lidar/src/lib.rs
> +    let theta_r = f32::to_radians(theta_r);
Also from the datasheet the LIDAR angle is measured in the clockwise direction so we will need to multiply `theta_l` by -1 in the initialization. The LIDAR angle reading will be in degrees and I wrote the code with the intention of using degrees throughout. The only place this currently has an impact is in the if statement where I am checking for 0 and 180 degrees. Do the trig calculations need to be in radians or can they be in degrees?

2024-11-13 10:02 UTC, BradenEverson commented on earthmover-lidar/src/lib.rs
> +    let theta_r = f32::to_radians(theta_r);
They do need to be in radians, Rust has no degree trig functions. I must've missed this during the check, I'll change the if statement to radians

2024-11-13 10:35 UTC, merged